import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { LogsPage } from "./LogsPage";
import { OperationalHarness } from "../../test/OperationalHarness";
import { configurationFixture, logPageFixture, logFixture, operationalCursor } from "../../test/operationalFixtures";
import { operationalApi, OperationalApiError } from "../../lib/operationalApi";
import type { OperationalLogPage } from "../../lib/operationalTypes";
afterEach(cleanup);
vi.mock("../../lib/pipelineApi", async importOriginal => { const original = await importOriginal<typeof import("../../lib/pipelineApi")>(); return { ...original, pipelineApi: { ...original.pipelineApi, verifyLocalWorkspaceToken: vi.fn(async () => configurationFixture) } }; });
vi.mock("../../lib/operationalApi", async importOriginal => { const original = await importOriginal<typeof import("../../lib/operationalApi")>(); return { ...original, operationalApi: { logs: vi.fn() } }; });
beforeEach(() => { vi.clearAllMocks(); vi.mocked(operationalApi.logs).mockResolvedValue(logPageFixture()); });
async function open(route = "/logs") { render(<OperationalHarness route={route}><LogsPage /></OperationalHarness>); fireEvent.click(screen.getByText("Test connect")); await screen.findByText(/budget_exhausted/); }
describe("UI-012 Logs", () => {
  test("initial list preserves server order, zero/null and independent severity/outcome", async () => { await open(); const list = screen.getByRole("list"); const rows = list.querySelectorAll("li"); expect(rows[0]).toHaveTextContent("info"); expect(rows[0]).toHaveTextContent("cancelled"); expect(rows[0]).toHaveTextContent("0 ms"); expect(rows[1]).toHaveTextContent("warning"); expect(rows[1]).toHaveTextContent("failed"); expect(rows[1]).toHaveTextContent("Not measured"); expect(rows[1]).toHaveTextContent("budget_exhausted"); });
  test.each(["request", "job"])("%s category resets cursor and sends exact backend filter", async category => { await open(`/logs?cursor=${encodeURIComponent(operationalCursor)}`); fireEvent.change(screen.getByLabelText("Category"), { target: { value: category } }); await waitFor(() => expect(operationalApi.logs).toHaveBeenLastCalledWith(expect.any(String), { category, level: undefined, cursor: undefined, limit: 50 }, expect.any(AbortSignal))); });
  test.each(["info", "warning", "error"])("severity %s is a server filter", async level => { await open(); fireEvent.change(screen.getByLabelText("Severity"), { target: { value: level } }); await waitFor(() => expect(operationalApi.logs).toHaveBeenLastCalledWith(expect.any(String), expect.objectContaining({ level }), expect.any(AbortSignal))); });
  test("opaque cursor paging uses exact value; expansion triggers no network read", async () => { await open(); fireEvent.click(screen.getAllByText("Record details")[0]); expect(screen.getByText("req_safe_012")).toBeVisible(); expect(screen.getByText("status_code")).toBeVisible(); expect(screen.getByText("true")).toBeVisible(); expect(operationalApi.logs).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByText("Next page")); await waitFor(() => expect(operationalApi.logs).toHaveBeenLastCalledWith(expect.any(String), expect.objectContaining({ cursor: operationalCursor }), expect.any(AbortSignal))); expect(screen.getByTestId("test-location")).toHaveTextContent(encodeURIComponent(operationalCursor)); });
  test("empty page is a real empty and cannot advance", async () => { vi.mocked(operationalApi.logs).mockResolvedValue({ items: [], has_more: false, next_cursor: null, limit: 50 }); render(<OperationalHarness><LogsPage /></OperationalHarness>); fireEvent.click(screen.getByText("Test connect")); await screen.findByText(/No records for these filters/); expect(screen.getByText("Next page")).toBeDisabled(); });
  test.each([404, 503])("HTTP %s does not become empty logs", async status => { vi.mocked(operationalApi.logs).mockRejectedValue(new OperationalApiError(status)); render(<OperationalHarness><LogsPage /></OperationalHarness>); fireEvent.click(screen.getByText("Test connect")); await screen.findByRole("alert"); expect(screen.queryByText(/No records for these filters/)).toBeNull(); });
  test("late page cannot repaint changed filter, including stale errors", async () => { let reject!: (error: Error) => void; vi.mocked(operationalApi.logs).mockImplementation((_token, params) => params?.category ? Promise.resolve({ ...logPageFixture(), items: [logFixture("tel_current")] }) : new Promise((_resolve, r) => { reject = r; })); render(<OperationalHarness><LogsPage /></OperationalHarness>); fireEvent.click(screen.getByText("Test connect")); await waitFor(() => expect(operationalApi.logs).toHaveBeenCalledTimes(1)); const signal = vi.mocked(operationalApi.logs).mock.calls[0][2]; fireEvent.change(screen.getByLabelText("Category"), { target: { value: "request" } }); await screen.findByText("Record details"); await act(async () => reject(new OperationalApiError(503))); expect(screen.queryByRole("alert")).toBeNull(); expect(signal?.aborted).toBe(true); });
  test("pending cursor page cannot overwrite a newer filter", async () => { let resolve!: (page: OperationalLogPage) => void; vi.mocked(operationalApi.logs).mockImplementation((_token, params) => params?.cursor ? new Promise(r => { resolve = r; }) : Promise.resolve(logPageFixture())); await open(); fireEvent.click(screen.getByText("Next page")); await waitFor(() => expect(operationalApi.logs).toHaveBeenCalledTimes(2)); fireEvent.change(screen.getByLabelText("Severity"), { target: { value: "error" } }); await screen.findByText(/budget_exhausted/); await act(async () => resolve({ ...logPageFixture(), items: [logFixture("tel_stale")] })); fireEvent.click(screen.getAllByText("Record details")[0]); expect(screen.queryByText("tel_stale")).toBeNull(); });
  test("disconnected performs no private calls and no false zero", () => { render(<OperationalHarness><LogsPage /></OperationalHarness>); expect(screen.getByText("Private data is not connected")).toBeVisible(); expect(operationalApi.logs).not.toHaveBeenCalled(); expect(screen.queryByText(/No records for these filters/)).toBeNull(); });
});
