import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { SettingsPage, type SettingsPageProps } from "./SettingsPage";
import { OperationalHarness } from "../../test/OperationalHarness";
import { configurationFixture, operationalToken } from "../../test/operationalFixtures";
import { operationalApi, OperationalApiError } from "../../lib/operationalApi";
import { pipelineApi } from "../../lib/pipelineApi";
import { conversationsToJson } from "../../lib/conversationExport";
import type { SettingsFacts } from "../../lib/operationalTypes";
vi.mock("../../lib/pipelineApi", async importOriginal => { const original = await importOriginal<typeof import("../../lib/pipelineApi")>(); return { ...original, pipelineApi: { ...original.pipelineApi, verifyLocalWorkspaceToken: vi.fn(async () => configurationFixture) } }; });
vi.mock("../../lib/operationalApi", async importOriginal => { const original = await importOriginal<typeof import("../../lib/operationalApi")>(); return { ...original, operationalApi: { settingsFacts: vi.fn(), configuration: vi.fn(), providerStatus: vi.fn() } }; });
afterEach(() => { cleanup(); localStorage.clear(); });
beforeEach(() => { vi.clearAllMocks(); vi.mocked(operationalApi.providerStatus).mockResolvedValue({ provider: "groq", configuration_status: "configured", credential_status: "configured", availability_status: "unknown" }); vi.mocked(operationalApi.settingsFacts).mockResolvedValue({ api_version: "1.0", default_retrieval: "balanced" }); vi.mocked(operationalApi.configuration).mockResolvedValue(configurationFixture); });
function props(): SettingsPageProps { return { theme: "system", onThemeChange: vi.fn(), storageMode: "indexeddb", storageWarning: null, writerStatus: { supported: true, owned: true, readOnly: false, reason: null }, onRequestWriter: vi.fn(async () => ({ supported: true, owned: true, readOnly: false, reason: null })), onExportBackup: vi.fn(), onImportBackup: vi.fn(async () => ({ imported: 1, persisted: 1, volatile: 0, failed: 0 })) }; }
function mount(value = props()) { return { ...render(<OperationalHarness route="/settings"><SettingsPage {...value} /></OperationalHarness>), props: value }; }
describe("UI-012 Settings", () => {
  test("safe current facts and fixed retention are read only with no unsupported mutation", async () => { mount(); await screen.findByText("balanced"); expect(screen.getByText("30 days")).toBeVisible(); expect(screen.getByText("7 days")).toBeVisible(); expect(screen.getByText("indexeddb")).toBeVisible(); expect(screen.queryByRole("button", { name: /save|apply|clear logs|provider selector/i })).toBeNull(); expect(screen.getByRole("link", { name: "View model/provider status" })).toHaveAttribute("href", "/models"); expect(operationalApi.configuration).not.toHaveBeenCalled(); });
  test("browser preferences invoke existing app owners and language convention", async () => { const value = props(); mount(value); fireEvent.change(screen.getByLabelText("Theme"), { target: { value: "dark" } }); expect(value.onThemeChange).toHaveBeenCalledExactlyOnceWith("dark"); fireEvent.change(screen.getByLabelText("Language"), { target: { value: "vi" } }); expect(screen.getByRole("heading", { name: "Cài đặt" })).toBeVisible(); await screen.findByText("balanced"); });
  test("shared connect clears password immediately and never persists or renders token", async () => { mount(); fireEvent.change(screen.getByLabelText("Local workspace token"), { target: { value: operationalToken } }); fireEvent.click(screen.getByRole("button", { name: "Connect" })); expect(screen.queryByDisplayValue(operationalToken)).toBeNull(); await screen.findByText("Connected · token held in memory only"); expect(pipelineApi.verifyLocalWorkspaceToken).toHaveBeenCalledExactlyOnceWith(operationalToken); expect(operationalApi.configuration).toHaveBeenCalledWith(operationalToken, expect.any(AbortSignal)); expect(document.body.textContent).not.toContain(operationalToken); expect(JSON.stringify(localStorage)).not.toContain(operationalToken); expect(JSON.stringify(sessionStorage)).not.toContain(operationalToken); });
  test("new app instance clears credential and protected facts", async () => { const app = mount(); fireEvent.click(screen.getByText("Test connect")); await screen.findByText("Connected · token held in memory only"); app.unmount(); mount(); expect(screen.getByLabelText("Local workspace token")).toHaveValue(""); expect(screen.queryByText("Connected · token held in memory only")).toBeNull(); });
  test("disconnect hides protected current configuration", async () => { mount(); fireEvent.click(screen.getByText("Test connect")); await screen.findByText("Deployment mode"); fireEvent.click(screen.getByRole("button", { name: "Disconnect" })); expect(screen.queryByText("Deployment mode")).toBeNull(); });
  test("public protected read failure remains unavailable, never disabled flags", async () => { vi.mocked(operationalApi.configuration).mockRejectedValue(new OperationalApiError(404)); mount(); fireEvent.click(screen.getByText("Test connect")); await screen.findByRole("alert"); expect(screen.queryByText("Disabled")).toBeNull(); });
  test("late facts cannot repaint after explicit refresh", async () => { let resolve!: (value: SettingsFacts) => void; vi.mocked(operationalApi.settingsFacts).mockImplementationOnce(() => new Promise(r => { resolve = r; })).mockResolvedValue({ api_version: "2.0", default_retrieval: "current" }); mount(); fireEvent.click(screen.getByRole("button", { name: "Refresh" })); await screen.findByText("current"); await act(async () => resolve({ api_version: "old", default_retrieval: "stale" })); expect(screen.queryByText("stale")).toBeNull(); });
  test("backup export reuses the existing owner", () => { const value = props(); mount(value); fireEvent.click(screen.getByText("Export backup")); expect(value.onExportBackup).toHaveBeenCalledTimes(1); });
  test("invalid import is refused before mutation", async () => { const value = props(); mount(value); fireEvent.change(screen.getByLabelText("Preview a backup to import"), { target: { files: [{ size: 5, text: async () => "{}" }] } }); await screen.findByText("The backup is invalid or exceeds 25 MiB."); expect(value.onImportBackup).not.toHaveBeenCalled(); expect(screen.queryByText("Confirm import")).toBeNull(); });
  test("valid import previews counts and requires one explicit confirmation", async () => { const value = props(); mount(value); fireEvent.change(screen.getByLabelText("Preview a backup to import"), { target: { files: [{ size: 200, name: "synthetic.json", text: async () => conversationsToJson([], []) }] } }); await screen.findByText("Confirm import"); expect(value.onImportBackup).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Import backup" })); await screen.findByText(/Imported 1; persisted 1/); expect(value.onImportBackup).toHaveBeenCalledTimes(1); });
  test("writer recovery displays actual result", async () => { const value = props(); mount(value); fireEvent.click(screen.getByText("Retry writer access")); await screen.findByText("Writer status: Writer owned"); expect(value.onRequestWriter).toHaveBeenCalledTimes(1); });
  test("stale protected configuration is ignored after disconnect", async () => { let resolve!: (value: typeof configurationFixture) => void; vi.mocked(operationalApi.configuration).mockImplementation(() => new Promise(r => { resolve = r; })); mount(); fireEvent.click(screen.getByText("Test connect")); await waitFor(() => expect(operationalApi.configuration).toHaveBeenCalledTimes(1)); fireEvent.click(screen.getByText("Test disconnect")); await act(async () => resolve(configurationFixture)); expect(screen.queryByText("Deployment mode")).toBeNull(); });
});
