import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { AnalyticsPanel } from "./AnalyticsPanel";
import { OperationalHarness } from "../test/OperationalHarness";
import { configurationFixture, seriesFixture, summaryFixture } from "../test/operationalFixtures";
import { operationalApi, OperationalApiError } from "../lib/operationalApi";
import { analyticsMetrics, analyticsRanges, type AnalyticsSummary } from "../lib/operationalTypes";
afterEach(cleanup);
vi.mock("../lib/pipelineApi", async importOriginal => { const original = await importOriginal<typeof import("../lib/pipelineApi")>(); return { ...original, pipelineApi: { ...original.pipelineApi, verifyLocalWorkspaceToken: vi.fn(async () => configurationFixture) } }; });
vi.mock("../lib/operationalApi", async importOriginal => { const original = await importOriginal<typeof import("../lib/operationalApi")>(); return { ...original, operationalApi: { summary: vi.fn(), timeseries: vi.fn() } }; });
async function open(route = "/analytics") { render(<OperationalHarness route={route}><AnalyticsPanel /></OperationalHarness>); fireEvent.click(screen.getByText("Test connect")); await screen.findByRole("heading", { name: "Terminal requests" }); }
beforeEach(() => { vi.clearAllMocks(); vi.mocked(operationalApi.summary).mockImplementation(async (_token, range) => summaryFixture(range)); vi.mocked(operationalApi.timeseries).mockImplementation(async (_token, range, interval, metric) => seriesFixture(range, interval, metric)); });
describe("UI-012 Analytics", () => {
  test("late timeseries cannot repaint a successor metric", async () => {
    let resolve!: (value: ReturnType<typeof seriesFixture>) => void;
    vi.mocked(operationalApi.timeseries).mockImplementation((_token, range, interval, metric) => metric === "request_count" ? new Promise(r => { resolve = r; }) : Promise.resolve(seriesFixture(range, interval, metric)));
    await open(); fireEvent.change(screen.getByLabelText("Metric"), { target: { value: "request_duration_p50_ms" } });
    await screen.findByRole("img"); await act(async () => resolve(seriesFixture()));
    expect(screen.getByRole("img")).toHaveAttribute("aria-label", expect.stringContaining("p50 measured duration")); expect(document.querySelectorAll(".operations-chart circle")).toHaveLength(1);
  });
  test("A→B→A starts a new read lifetime and cannot reuse the first A population", async () => {
    await open(); let resolve!: (value: AnalyticsSummary) => void;
    vi.mocked(operationalApi.summary).mockImplementation(() => new Promise(r => { resolve = r; }));
    fireEvent.change(screen.getByLabelText("Time range"), { target: { value: "7d" } });
    fireEvent.change(screen.getByLabelText("Time range"), { target: { value: "24h" } });
    expect(screen.queryByText("40%")).toBeNull(); await act(async () => resolve(summaryFixture())); await screen.findByText("40%");
  });
  test("401 invalidates the current session and preserves an actionable unauthorized state", async () => {
    vi.mocked(operationalApi.summary).mockRejectedValue(new OperationalApiError(401));
    render(<OperationalHarness><AnalyticsPanel /></OperationalHarness>); fireEvent.click(screen.getByText("Test connect"));
    await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("token was rejected")); expect(screen.getByLabelText("Local workspace token")).toBeVisible(); expect(screen.queryByText("40%")).toBeNull();
  });
  test("disconnected is unavailable rather than zero and issues no private read", () => { render(<OperationalHarness><AnalyticsPanel /></OperationalHarness>); expect(screen.getByText("Private data is not connected")).toBeVisible(); expect(screen.queryByText("Terminal requests")).toBeNull(); expect(operationalApi.summary).not.toHaveBeenCalled(); });
  test.each(analyticsRanges)("direct %s renders server rates, populations, real zero and jobs", async range => { await open(`/analytics?range=${range}`); expect(operationalApi.summary).toHaveBeenCalledWith(expect.any(String), range, expect.any(AbortSignal)); expect(screen.getByText("2 / 5 requests")).toBeVisible(); expect(screen.getByText("1 / 5 requests")).toBeVisible(); expect(screen.getByText("40%")).toBeVisible(); expect(screen.getByText("0 ms")).toBeVisible(); expect(screen.getByText("2 measured · 3 not measured")).toBeVisible(); expect(screen.getByText("Terminal jobs · 4")).toBeVisible(); expect(document.body.textContent).not.toMatch(/token usage|CPU|memory usage|cost|confidence|uptime|local events/i); });
  test("range switch reads summary/series once; metric/interval switches do not refetch summary", async () => { await open(); fireEvent.change(screen.getByLabelText("Time range"), { target: { value: "7d" } }); await waitFor(() => expect(operationalApi.summary).toHaveBeenCalledTimes(2)); fireEvent.change(screen.getByLabelText("Metric"), { target: { value: "request_duration_p95_ms" } }); fireEvent.change(screen.getByLabelText("Interval"), { target: { value: "day" } }); await waitFor(() => expect(operationalApi.timeseries).toHaveBeenLastCalledWith(expect.any(String), "7d", "day", "request_duration_p95_ms", expect.any(AbortSignal))); expect(operationalApi.summary).toHaveBeenCalledTimes(2); expect(screen.getByTestId("test-location")).toHaveTextContent("range=7d&metric=request_duration_p95_ms&interval=day"); });
  test.each(analyticsMetrics)("%s uses returned buckets with an accessible table and no interpolation", async metric => { await open(`/analytics?metric=${metric}`); await screen.findByRole("img"); fireEvent.click(screen.getByText(/Bucket table and populations/)); expect(screen.getByRole("table")).toBeVisible(); const points = document.querySelectorAll(".operations-chart circle"); expect(points.length).toBe(metric.includes("duration") ? 1 : 2); expect(document.querySelectorAll(".operations-chart polyline, .operations-chart path")).toHaveLength(0); if (metric.includes("duration")) { expect(within(screen.getByRole("table")).getByText("Not measured")).toBeVisible(); expect(within(screen.getByRole("table")).getByText("0 ms")).toBeVisible(); } });
  test("empty duration population stays unavailable, defined counts stay zero", async () => { vi.mocked(operationalApi.summary).mockResolvedValue(summaryFixture("24h", true)); vi.mocked(operationalApi.timeseries).mockResolvedValue(seriesFixture("24h", "hour", "request_duration_p50_ms", true)); await open("/analytics?metric=request_duration_p50_ms"); expect(screen.getByText("No terminal requests recorded in this range.")).toBeVisible(); expect(screen.getByText("No measured population in this range.")).toBeVisible(); expect(screen.queryByText("0 ms")).toBeNull(); expect(screen.getAllByText("0 / 0 requests")).toHaveLength(2); });
  test.each([404, 503, 422])("HTTP %s remains an error, never fake empty", async status => { vi.mocked(operationalApi.summary).mockRejectedValue(new OperationalApiError(status)); render(<OperationalHarness><AnalyticsPanel /></OperationalHarness>); fireEvent.click(screen.getByText("Test connect")); await waitFor(() => expect(screen.getAllByRole("alert").length).toBeGreaterThan(0)); expect(screen.queryByText("No terminal requests recorded in this range.")).toBeNull(); });
  test("late 24h success cannot repaint 7d even if transport ignores abort", async () => { let resolve!: (value: AnalyticsSummary) => void; vi.mocked(operationalApi.summary).mockImplementation((_token, range) => range === "24h" ? new Promise(r => { resolve = r; }) : Promise.resolve({ ...summaryFixture(range), requests: { ...summaryFixture(range).requests, terminal_count: 77 } })); render(<OperationalHarness><AnalyticsPanel /></OperationalHarness>); fireEvent.click(screen.getByText("Test connect")); await waitFor(() => expect(operationalApi.summary).toHaveBeenCalledTimes(1)); const signal = vi.mocked(operationalApi.summary).mock.calls[0][2]; fireEvent.change(screen.getByLabelText("Time range"), { target: { value: "7d" } }); await screen.findByText("77"); await act(async () => resolve(summaryFixture())); expect(screen.getByText("77")).toBeVisible(); expect(signal?.aborted).toBe(true); });
  test("disconnect invalidates pending reads and hides prior server facts", async () => { await open(); fireEvent.click(screen.getByText("Test disconnect")); expect(screen.queryByText("40%")).toBeNull(); expect(screen.getByText("Private data is not connected")).toBeVisible(); });
});
