import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, BarChart3, ClipboardCheck, GitCompareArrows, LineChart, ListChecks, LoaderCircle, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { useLocale } from "../lib/i18n";
import { evaluationErrorMessage } from "../lib/evaluationApi";
import type { FailureCategory, NativeMetricId, PublishedSummary } from "../lib/evaluationTypes";
import { isNativeReport } from "../lib/evaluationTypes";
import { ComparisonResults, FailuresView, TrendsView, failureLabels } from "./evaluation/EvaluationAnalytics";
import { EvaluationJobs } from "./evaluation/EvaluationJobs";
import { NativeCases, NativeMetrics } from "./evaluation/NativeMetrics";
import { useEvaluationCatalog, useEvaluationCompare, useEvaluationFailures, useEvaluationTrends } from "./evaluation/useEvaluationPublic";
import { Tabs } from "./ui/Foundation";

type Surface = "overview" | "compare" | "trends" | "failures" | "jobs";
interface EvaluationPanelProps {
  selectedId?: string | null;
  selectedSource?: "report" | "job";
  onSelectReport?: (id: string) => void;
  onSelectJob?: (id: string) => void;
}
function date(value: string, locale: "en" | "vi") { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleString(locale === "vi" ? "vi-VN" : "en-US"); }
function reportName(report: PublishedSummary) { return isNativeReport(report) ? report.run_id : report.title; }

export function EvaluationPanel({ selectedId = null, selectedSource = "report", onSelectReport = () => {}, onSelectJob = () => {} }: EvaluationPanelProps) {
  const { locale } = useLocale(); const vi = locale === "vi";
  const [surface, setSurface] = useState<Surface>(selectedSource === "job" ? "jobs" : "overview");
  const [search, setSearch] = useState("");
  const [baseline, setBaseline] = useState(""); const [candidate, setCandidate] = useState("");
  const [trendMetric, setTrendMetric] = useState<NativeMetricId>("native.faithfulness");
  const [failureRun, setFailureRun] = useState(""); const [failureCategory, setFailureCategory] = useState<FailureCategory | "all">("all");
  const [resultsPage, setResultsPage] = useState(1);
  const selectedReportId = selectedSource === "report" ? selectedId : null;
  const selectedJobId = selectedSource === "job" ? selectedId : null;
  const catalog = useEvaluationCatalog(selectedReportId, resultsPage);
  const compare = useEvaluationCompare(); const trends = useEvaluationTrends(); const failures = useEvaluationFailures();
  const definitions = catalog.metrics?.items ?? [];
  const nativeReports = useMemo(() => catalog.reports.filter(isNativeReport), [catalog.reports]);
  const visibleReports = useMemo(() => {
    const needle = search.trim().toLocaleLowerCase(locale);
    return needle ? catalog.reports.filter((item) => `${reportName(item)} ${item.run_id}`.toLocaleLowerCase(locale).includes(needle)) : catalog.reports;
  }, [catalog.reports, locale, search]);
  useEffect(() => { if (selectedSource === "job") setSurface("jobs"); else if (selectedId) setSurface("overview"); }, [selectedId, selectedSource]);
  useEffect(() => { setResultsPage(1); }, [selectedReportId]);
  useEffect(() => {
    if (!baseline && nativeReports[0]) setBaseline(nativeReports[0].run_id);
    if (!candidate && nativeReports[1]) setCandidate(nativeReports[1].run_id);
    if (!failureRun && nativeReports[0]) setFailureRun(nativeReports[0].run_id);
  }, [baseline, candidate, failureRun, nativeReports]);
  useEffect(() => { if (surface === "trends") trends.load(trendMetric); }, [surface, trendMetric]);
  useEffect(() => { if (surface === "failures" && failureRun) failures.load(failureRun, failureCategory === "all" ? undefined : failureCategory); else if (surface === "failures") failures.clear(); }, [surface, failureRun, failureCategory]);
  const selectedNative = catalog.detail && isNativeReport(catalog.detail) ? catalog.detail : null;
  const selectedLegacy = catalog.detail && !isNativeReport(catalog.detail) ? catalog.detail : null;
  const sections: Array<{ id: Surface; label: string; icon: typeof Activity }> = [
    { id: "overview", label: "Reports", icon: ClipboardCheck }, { id: "compare", label: vi ? "So sánh" : "Compare", icon: GitCompareArrows },
    { id: "trends", label: vi ? "Xu hướng" : "Trends", icon: LineChart }, { id: "failures", label: "Failures", icon: BarChart3 },
    { id: "jobs", label: vi ? "Jobs riêng tư" : "Private jobs", icon: ListChecks },
  ];
  return <section className="workspace-page workspace-page--wide evaluation-workspace console-view-enter" aria-labelledby="evaluation-title">
    <header className="console-page-header"><div className="console-page-header__identity"><div className="console-page-header__icon"><ClipboardCheck /></div><div><h1 id="evaluation-title" className="console-page-header__title">Evaluation</h1><p className="console-page-header__subtitle">{vi ? "Định nghĩa native, báo cáo public và job frozen có ngân sách—không có chỉ số demo." : "Native definitions, public reports and budgeted frozen jobs—without demo metrics."}</p></div></div><div className="console-page-header__actions"><span className="evaluation-native-chip"><ShieldCheck />Native evaluation v{catalog.metrics?.protocol_version ?? 1}</span><button type="button" className="console-btn" onClick={catalog.refreshCatalog}><RefreshCw className={catalog.loading ? "animate-spin" : ""} />{vi ? "Làm mới" : "Refresh"}</button></div></header>
    <Tabs className="evaluation-nav" label={vi ? "Evaluation workspace" : "Evaluation workspace sections"} value={surface} onValueChange={(value) => setSurface(value as Surface)} options={sections.map(({ id, label, icon: Icon }) => ({ id, panelId: `evaluation-panel-${id}`, label: <><Icon aria-hidden="true" />{label}</> }))} />
    {catalog.errorStatus !== null && <div role="alert" className="evaluation-alert"><AlertTriangle />{evaluationErrorMessage(catalog.errorStatus, locale)}<button type="button" className="console-btn" onClick={catalog.refreshCatalog}>{vi ? "Thử lại" : "Try again"}</button></div>}
    {catalog.loading && !catalog.metrics ? <div className="evaluation-empty" role="status"><LoaderCircle className="animate-spin" /><strong>{vi ? "Đang tải evaluation…" : "Loading evaluation…"}</strong></div>
      : catalog.metrics && <NativeMetrics definitions={definitions} aggregates={selectedNative?.aggregates ?? []} locale={locale} />}

    <div id={`evaluation-panel-${surface}`} role="tabpanel" aria-label={sections.find((section) => section.id === surface)?.label} className="evaluation-active-panel">
    {surface === "overview" && <div className="evaluation-overview">
      <section className="console-card evaluation-reports" aria-labelledby="evaluation-runs-title"><div className="console-card__header"><div><h2 id="evaluation-runs-title">{vi ? "Báo cáo đã publish" : "Published reports"}</h2><p>{catalog.total} {vi ? "báo cáo public đã được backend xác thực" : "backend-validated public reports"}</p></div><label className="evaluation-search"><Search /><span className="sr-only">{vi ? "Tìm báo cáo" : "Search reports"}</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={vi ? "Tìm run…" : "Search runs…"} /></label></div>
        {visibleReports.length === 0 ? <div className="evaluation-empty"><strong>{catalog.reports.length === 0 ? (vi ? "Chưa có báo cáo public" : "No published reports yet") : (vi ? "Không có report phù hợp" : "No matching reports")}</strong><p>{vi ? "Không có dữ liệu thay thế, trend demo hay điểm được suy diễn." : "No substitute data, demo trends or inferred scores are shown."}</p></div>
          : <div className="evaluation-report-list">{visibleReports.map((report) => <button type="button" key={report.run_id} className={selectedReportId === report.run_id ? "is-selected" : ""} onClick={() => onSelectReport(report.run_id)}><span><strong>{reportName(report)}</strong><small>{report.run_id}</small></span><span>{isNativeReport(report) ? <><span className="evaluation-state evaluation-state--native">native v{report.protocol_version}</span><small>{report.binding.dataset_id} · {report.case_count} cases</small></> : <><span className="evaluation-state evaluation-state--legacy">legacy</span><small>{report.case_count} cases</small></>}</span><span><span className={`evaluation-state evaluation-state--${report.status}`}>{report.status}</span><small>{date(isNativeReport(report) ? report.published_at : report.created_at, locale)}</small></span></button>)}</div>}
      </section>
      <aside className="console-card evaluation-report-detail" aria-label={vi ? "Chi tiết báo cáo" : "Report detail"}>
        {!selectedReportId ? <div className="evaluation-empty"><Activity /><strong>{vi ? "Chọn một báo cáo" : "Select a report"}</strong><p>{vi ? "Mở report theo ID canonical để xem binding, denominator và case metric an toàn." : "Open a canonical report ID to inspect bindings, denominators and safe case metrics."}</p></div>
          : catalog.detailLoading && !catalog.detail ? <div className="evaluation-empty" role="status"><LoaderCircle className="animate-spin" /><strong>{vi ? "Đang tải report…" : "Loading report…"}</strong></div>
          : catalog.detailErrorStatus !== null ? <div role="alert" className="evaluation-alert"><AlertTriangle />{evaluationErrorMessage(catalog.detailErrorStatus, locale)}</div>
          : selectedNative ? <><div className="console-card__header"><div><h2>{selectedNative.run_id}</h2><p>{date(selectedNative.published_at, locale)}</p></div><span className={`evaluation-state evaluation-state--${selectedNative.status}`}>{selectedNative.status}</span></div><div className="console-card__body evaluation-report-body"><dl className="evaluation-job-facts"><div><dt>{vi ? "Dataset" : "Dataset"}</dt><dd>{selectedNative.binding.dataset_id} · {selectedNative.binding.dataset_revision}</dd></div><div><dt>{vi ? "Generator" : "Generator"}</dt><dd>{selectedNative.binding.generator_model_id}</dd></div><div><dt>{vi ? "Judge" : "Judge"}</dt><dd>{selectedNative.binding.judge_model_id ?? (vi ? "Chưa được báo cáo" : "Not reported")}</dd></div><div><dt>Cases</dt><dd>{selectedNative.case_count}</dd></div><div><dt>Report digest</dt><dd>{selectedNative.report_digest}</dd></div><div><dt>Publication</dt><dd>{selectedNative.status}</dd></div></dl><details><summary>{vi ? "Binding đầy đủ" : "Full binding"}</summary><dl className="evaluation-provenance"><div><dt>Generation</dt><dd>{selectedNative.binding.generation_binding}</dd></div><div><dt>Retrieval</dt><dd>{selectedNative.binding.retrieval_binding}</dd></div><div><dt>Context</dt><dd>{selectedNative.binding.context_binding}</dd></div><div><dt>Judge</dt><dd>{selectedNative.binding.judge_binding ?? (vi ? "Chưa được báo cáo" : "Not reported")}</dd></div></dl></details>{catalog.results && <NativeCases items={catalog.results.items} definitions={catalog.results.metric_definitions} total={catalog.results.total} page={catalog.results.page} pageSize={catalog.results.page_size} onPage={setResultsPage} locale={locale} />}</div></>
          : selectedLegacy ? <><div className="console-card__header"><div><h2>{selectedLegacy.title}</h2><p>{selectedLegacy.run_id}</p></div><span className="evaluation-state evaluation-state--legacy">legacy · {selectedLegacy.status}</span></div><div className="console-card__body"><p className="evaluation-note">{vi ? "Báo cáo tương thích cũ được hiển thị ở chế độ metadata an toàn. Nó không tham gia native compare, trends hoặc failures." : "This legacy compatibility report is shown as safe metadata only. It cannot enter native comparison, trends or failures."}</p><dl className="evaluation-job-facts"><div><dt>{vi ? "Ngày" : "Date"}</dt><dd>{date(selectedLegacy.created_at, locale)}</dd></div><div><dt>Cases</dt><dd>{selectedLegacy.case_count}</dd></div><div><dt>{vi ? "Điểm được ghi" : "Recorded aggregates"}</dt><dd>{Object.entries(selectedLegacy.aggregate).map(([key, value]) => `${key}=${value}`).join(", ") || (vi ? "Chưa được báo cáo" : "Not reported")}</dd></div></dl></div></> : null}
      </aside>
    </div>}
    {surface === "compare" && <section className="console-card evaluation-tool" aria-labelledby="evaluation-compare-title"><div className="console-card__header"><div><h2 id="evaluation-compare-title">{vi ? "So sánh native" : "Native comparison"}</h2><p>{vi ? "Backend quyết định compatibility, denominator và candidate − baseline." : "The backend owns compatibility, denominators and candidate − baseline."}</p></div></div><form className="evaluation-tool-form" onSubmit={(event) => { event.preventDefault(); if (baseline && candidate) compare.compare(baseline, candidate); }}><label>Baseline<select value={baseline} onChange={(event) => setBaseline(event.target.value)}><option value="">{vi ? "Chọn report" : "Choose report"}</option>{nativeReports.map((report) => <option key={report.run_id} value={report.run_id}>{report.run_id}</option>)}</select></label><label>Candidate<select value={candidate} onChange={(event) => setCandidate(event.target.value)}><option value="">{vi ? "Chọn report" : "Choose report"}</option>{nativeReports.map((report) => <option key={report.run_id} value={report.run_id}>{report.run_id}</option>)}</select></label><button type="submit" className="console-btn console-btn--primary" disabled={!baseline || !candidate || baseline === candidate || compare.loading}>{compare.loading ? <LoaderCircle className="animate-spin" /> : <GitCompareArrows />}{vi ? "So sánh" : "Compare"}</button></form>{nativeReports.length < 2 && <div className="evaluation-empty"><strong>{vi ? "Không có đủ báo cáo native để so sánh" : "No comparable pair yet"}</strong><p>{vi ? "Cần ít nhất hai publication native. Private job chưa publish không được dùng thay thế." : "At least two native publications are required. An unpublished private job is not a substitute."}</p></div>}{compare.errorStatus !== null && <div role="alert" className="evaluation-alert"><AlertTriangle />{evaluationErrorMessage(compare.errorStatus, locale)}</div>}{compare.comparison && <ComparisonResults comparison={compare.comparison} definitions={definitions} locale={locale} />}</section>}
    {surface === "trends" && <section className="console-card evaluation-tool" aria-labelledby="evaluation-trends-title"><div className="console-card__header"><div><h2 id="evaluation-trends-title">{vi ? "Xu hướng native" : "Native trends"}</h2><p>{vi ? "Các observation publish được nhóm theo binding; không nội suy hoặc làm mượt." : "Published observations grouped by binding, without interpolation or smoothing."}</p></div><label>{vi ? "Chỉ số" : "Metric"}<select value={trendMetric} onChange={(event) => setTrendMetric(event.target.value as NativeMetricId)}>{definitions.map((definition) => <option value={definition.metric_id} key={definition.metric_id}>{definition.label}</option>)}</select></label></div>{trends.loading && <div role="status" className="evaluation-empty"><LoaderCircle className="animate-spin" /><strong>{vi ? "Đang tải trends…" : "Loading trends…"}</strong></div>}{trends.errorStatus !== null && <div role="alert" className="evaluation-alert"><AlertTriangle />{evaluationErrorMessage(trends.errorStatus, locale)}</div>}{trends.trends && <TrendsView trends={trends.trends} definitions={definitions} locale={locale} />}</section>}
    {surface === "failures" && <section className="console-card evaluation-tool" aria-labelledby="evaluation-failures-title"><div className="console-card__header"><div><h2 id="evaluation-failures-title">{vi ? "Failure taxonomy native" : "Native failure taxonomy"}</h2><p>{vi ? "Chỉ dùng bốn category backend, không dùng ngưỡng tùy ý." : "Only the four backend categories; no arbitrary thresholds."}</p></div></div><form className="evaluation-tool-form" onSubmit={(event) => { event.preventDefault(); if (failureRun) failures.load(failureRun, failureCategory === "all" ? undefined : failureCategory); }}><label>Report<select value={failureRun} onChange={(event) => setFailureRun(event.target.value)}><option value="">{vi ? "Chọn report" : "Choose report"}</option>{nativeReports.map((report) => <option key={report.run_id} value={report.run_id}>{report.run_id}</option>)}</select></label><label>Category<select value={failureCategory} onChange={(event) => setFailureCategory(event.target.value as FailureCategory | "all")}><option value="all">{vi ? "Tất cả" : "All categories"}</option>{Object.entries(failureLabels).map(([id, label]) => <option value={id} key={id}>{label[locale]}</option>)}</select></label><button type="submit" className="console-btn" disabled={!failureRun || failures.loading}>{vi ? "Áp dụng" : "Apply"}</button></form>{nativeReports.length === 0 && <div className="evaluation-empty"><strong>{vi ? "Chưa có publication native" : "No native publication yet"}</strong><p>{vi ? "Không có failure demo được tạo." : "No demo failures are generated."}</p></div>}{failures.loading && <div role="status" className="evaluation-empty"><LoaderCircle className="animate-spin" /><strong>{vi ? "Đang tải failures…" : "Loading failures…"}</strong></div>}{failures.errorStatus !== null && <div role="alert" className="evaluation-alert"><AlertTriangle />{evaluationErrorMessage(failures.errorStatus, locale)}</div>}{failures.failures && <FailuresView failures={failures.failures} definitions={definitions} locale={locale} />}</section>}
    {surface === "jobs" && <EvaluationJobs selectedJobId={selectedJobId} onSelectJob={onSelectJob} definitions={definitions} locale={locale} />}
    </div>
  </section>;
}
